name: gp-mpc-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip=24.0
  - gym=0.26.1
  - matplotlib=3.8.4
  - cyipopt=1.1.0
  - moviepy=1.0.3
  - pip:
      - pygame==2.1.0
